name: "🔒 Security Vulnerability Report"
description: "🚨 Report a potential security vulnerability in the project."
title: "🔒 SECURITY - <title>"
labels:
  - "security"
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        ⚠ **IMPORTANT:** Please **DO NOT** disclose sensitive details in this public report.  
        If the vulnerability is critical, contact us securely at [info@caronte.site] or another secure channel.

  - type: textarea
    id: summary
    attributes:
      label: "📝 Summary"
      description: "📌 Briefly describe the identified security vulnerability."
      placeholder: "E.g., 🔥 The authentication token is exposed in the browser console."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "🔍 Steps to Reproduce"
      description: "🛠 Provide a clear, step-by-step guide to reproduce the vulnerability."
      placeholder: |
        1️⃣ Go to '...'
        2️⃣ Enter '...' in the input field
        3️⃣ Click on '...'
        4️⃣ 🚨 See the security issue
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "🎯 Describe how the system should behave without this vulnerability."
      placeholder: "E.g., 🔐 User authentication tokens should not be visible in client-side logs."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "⚠️ Describe the unintended behavior caused by this vulnerability."
      placeholder: "E.g., 🔓 The token is stored in local storage and can be accessed by any script."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "🚨 Security Impact"
      description: "🔎 Explain the potential risks and consequences of this vulnerability."
      placeholder: |
        - 🕵️ Data leakage
        - 🏴‍☠️ Privilege escalation
        - 💥 Remote code execution
    validations:
      required: true

  - type: textarea
    id: suggested_fixes
    attributes:
      label: "🛠 Suggested Fixes (if any)"
      description: "💡 Provide any potential solutions or mitigation strategies."
      placeholder: "E.g., Implement HTTP-only and Secure flags on authentication cookies."

  - type: textarea
    id: additional_info
    attributes:
      label: "📄 Additional Information"
      description: "📎 Provide any other relevant details, references, or external resources."
      placeholder: "E.g., Links to CVEs, OWASP references, related documentation."
