# Generated by Django 5.2 on 2025-04-15 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_goals_scored_away_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_week',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
