# Generated by Django 5.2 on 2025-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_match_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
