# Generated by Django 5.2 on 2025-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_competition_name_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='statsbomb_id',
        ),
    ]
