# Generated by Django 5.2 on 2025-04-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='representation',
            field=models.BooleanField(default=False),
        ),
    ]
