# Generated by Django 5.2 on 2025-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_event_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Teams won prediction', 'Teams won prediction'), ('Starting XI', 'Starting XI'), ('Ball Receipt*', 'Ball Receipt*'), ('Ball Recovery', 'Ball Recovery'), ('Dispossessed', 'Dispossessed'), ('Duel', 'Duel'), ('Block', 'Block'), ('Offside', 'Offside'), ('Clearance', 'Clearance'), ('Interception', 'Interception'), ('Dribble', 'Dribble'), ('Shot', 'Shot'), ('Pressure', 'Pressure'), ('Half Start', 'Half Start'), ('Substitution', 'Substitution'), ('Own Goal Against', 'Own Goal Against'), ('Foul Won', 'Foul Won'), ('Foul Committed', 'Foul Committed'), ('Goal Keeper', 'Goal Keeper'), ('Bad Behaviour', 'Bad Behaviour'), ('Own Goal For', 'Own Goal For'), ('Player On', 'Player On'), ('Player Off', 'Player Off'), ('Shield', 'Shield'), ('Pass', 'Pass'), ('50/50', '50/50'), ('Half End', 'Half End'), ('Error', 'Error'), ('Miscontrol', 'Miscontrol'), ('Dribbled Past', 'Dribbled Past'), ('Injury Stoppage', 'Injury Stoppage'), ('Referee Ball-Drop', 'Referee Ball-Drop'), ('Carry', 'Carry')], max_length=50),
        ),
    ]
